export const ACTIONS = {
    FETCH_MOVIES: 'FETCH_MOVIES',
    SEARCH_MOVIES: 'SEARCH_MOVIES', 
    ADD_MOVIE: 'ADD_MOVIE',
    REMOVE_MOVIE: 'REMOVE_MOVIE',
    EDIT_MOVIE: 'EDIT_MOVIE',
    SORT_MOVIES: 'SORT_MOVIES',
    FILTER_MOVIES: 'FILTER_MOVIES'
}
